rigtorp/awesome-modern-cpp

- README.md
I'll let you be the judge as to whether this is "awesome" enough. cpptoml is a modern C++11 header-only library for parsing [TOML](https://github.com/toml-lang/toml) configuration files.
> Add cpptoml TOML parsing library.

- README.md
Added definitive book list from stackoverflow, a link to /r/cpp_questions, and a few videos.
> A few of my favorites

- README.md
> Update banditcpp url

- README.md
Would you be willing to add the links to my blog and book to this list? Though not as general as Effective Modern C++, my book does target C++11 (and C++17 with the 2nd edition now available for Early Access), and my blog is reasonably popular.
> Added links to my blog and book

- README.md
https://github.com/effolkronium/random
This is high convenient random for modern C++ in the world!
> Add random for Modern C++ library

- README.md
Catch2 has been released and now lives in a different place.
> Point to latest Catch

- README.md
added  [sqlite_modern_cpp](https://github.com/SqliteModernCpp/sqlite_modern_cpp)
> Add sqlite_modern_cpp

- README.md
Added [Fluent C++](https://www.fluentcpp.com/) blog by [Jonathan Boccara](https://github.com/joboccara)
> added new cpp blog

- README.md
I think [Inja](https://github.com/pantor/inja) might be a good fit for this collection.
> Add Inja Template Engine

- README.md
[Drogon](https://github.com/an-tao/drogon)
> Add a link to the Drogon framework

- README.md
It's a great library. I hope other people like it as well!
> Added EnTT to the list of useful libraries

- README.md
[Oat++ Web Framework](https://github.com/oatpp/oatpp)
> Add oat++ web framework to the list

- README.md
I have been using fakeit since a couple months and it's wonderful and indispensable. It's license is MIT so free to use by anyone.
> Adding fakeit

- README.md
std::algorithm is really useful for writing simple modern c++. I added a couple talks that were useful for me when I was getting started learning about it. 
If there is interest I'd be happy to put in more work in curating the talks list with more. Put in summaries, group them logically, etc.
> Add talks about std::algorithm

- README.md
The C & C++ Users Group in Brazil
> C++ Brazil

- README.md
> add pprint

- README.md
As PostgreSQL is widely and commonly used database, here's the link to the official C++ client for PostgreSQL.
> Added C++ client API link for PostgreSQL database

- README.md
I recently released Font Chef, which is mainly a C library but it's C++ wrapper is first-class and expressive on it's own. Although it's not C++ only I believe it fits here. Sorry if I'm mistaken :)
> Adds Font Chef

- README.md
The book claims to be "On the Fly". Its intent is to provide a comprehensive introduction to the relevant features regarding modern C++ (before 2020s).
Ref: https://github.com/changkun/modern-cpp-tutorial
> Add new Book "Modern C++ Tutorial: C++ 11/14/17/20"

- README.md
Hi there, we are a research group working on a modern C++ library for analysing biological data. We saw your great list of modern C++ references and would like to be part of it.
> Add the SeqAn library to Awesome Modern C++

- README.md
It's a great benchmark, single-header and easy to plug into your project.
> Add nanobench

- README.md
Added the TinyORM modern C++ ORM library to the Database list.
[TinyORM](https://github.com/silverqx/TinyORM) - Modern C++ ORM library. [MIT] [website](https://www.tinyorm.org/)
> Database: Add TinyORM modern C++ ORM library
